name: INF 380P Fall 2022

title: INF 380P

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

future: true

timezone: America/Chicago

github_repo_url: https://github.com/inf380p/inf380p.github.io
gitter_room: inf380p/fall2022
zoom_url: https://utexas.zoom.us/j/98637940963
canvas_url: https://utexas.instructure.com/courses/1340523
office_hours_url: https://bit.ly/officehourswithdrhauser

# Add Runestone course url if not using Canvas LTI
runestone_course: https://runestone.academy/ns/books/published/inf380p2022/index.html

plugins:
  - jemoji

# Categories to exclude from the index
special-categories:
  - "exercise"
  - "how-to"
  - "sidebar"
  - "reading"
  - "notes"

# Don't serve these files/dirs.
exclude: [vendor, script]

# These can contain uppercase: they'll be lowercased in the URL
page-order:
  - syllabus
  - materials
  - how-to
  - people

# Same note RE case above
python-extra-pages:
  - console


permalink: none

# If this gets archived at a different URL make sure to delete the blank statements at the bottom
baseurl: /fall2022
url: /fall2022

python: true

course:
  title: Introduction to Programming
  number: INF 380P
  instructor: Prof. Elliott Hauser
  ta: TBD
  semester: Fall 2022
  location: "UTA 1.208"

authors:
  elliott:
    name: Elliott Hauser
    prof: true
    gravatar: 0d0d432948d262195358f339768f1240
    website: https://www.elliotthauser.com
    github: eah13
    twitter: hauspoor
    about:  "Elliott Hauser is an Assistant Professor at the UT Austin iSchool.  He's hacking education as one of the cofounders of Trinket.io."

  hannahmoutran:
    name: Hannah Moutran
    prof: false
    gravatar: 
    website: 
    github: hannahmoutran
    twitter: 
    about:  "Hannah Moutran is a first year graduate student at UT's iSchool."
    
  tommytestertwo:
    name: Tommy Tester
    prof: false
    gravatar:
    website: "https://en.wikipedia.org/wiki/Turtle"
    github: tommytestertwo
    twitter:
    about: "Testin' course websites since 2014."
  
  unixEnthusiast:
    name: Nikhil Singh
    prof: false
    gravatar:
    website: "https://en.m.wikipedia.org/wiki/Alan_Turing"
    github: unixEnthusiast
    twitter: 
    about: "Passing some time.. writing some code..."
    
  mchakerautexas:
    name: Mufaddal Chakera
    prof: false
    gravatar:
    website: "https://linuxtorvalds.com/"
    github: mchakerautexas
    twitter:
    about: "Learning how to code here!"

  alm7468:
    name: April Martin
    prof: false
    gravatar:
    website: "#"
    github: alm7468
    twitter:
    about: "April Martin is a MSIS student focusing on physical and digital preservation in libraries, archives, and museums, at the UT Austin iSchool."
    
  amptex101:
    name: amptex101
    prof: false
    gravatar:
    website: "#"
    github: amptex101
    twitter:
    about: "Here's a little about amptex101"
    
  atUtexas:
    name: atUtexas
    prof: false
    gravatar:
    website: "#"
    github: atUtexas
    twitter:
    about: "Here's a little about atUtexas"
    
  emmtm:
    name: emmtm
    prof: false
    gravatar:
    website: "#"
    github: emmtm
    twitter:
    about: "Here's a little about emmtm"
    
  EnglandHam:
    name: EnglandHam
    prof: false
    gravatar:
    website: "#"
    github: EnglandHam
    twitter:
    about: "Here's a little about EnglandHam"
    
  Eros11on:
    name: Eros11on
    prof: false
    gravatar:
    website: "#"
    github: Eros11on
    twitter:
    about: "Here's a little about Eros11on"
    
  greencouchpotato:
    name: Jyotsna Vempati
    prof: false
    gravatar:
    website: "linkedin.com/in/jyotsnavempati"
    github: greencouchpotato
    twitter: na
    about: "I'm a first year grad student at School of Information, UT. I'm specialising in UX Design."
    
  haley-triem:
    name: haley-triem
    prof: false
    gravatar:
    website: "#"
    github: haley-triem
    twitter:
    about: "With a typing speed of 90wpm and 100% acruacy, Haley is a coding whiz."
    
  hannahmoutran:
    name: hannahmoutran
    prof: false
    gravatar:
    website: "#"
    github: hannahmoutran
    twitter:
    about: "Here's a little about hannahmoutran"
    
  hyo9292:
    name: hyo9292
    prof: false
    gravatar:
    website: "#"
    github: hyo9292
    twitter:
    about: "Here's a little about hyo9292"
    
  iLiekatz:
    name: iLiekatz
    prof: false
    gravatar:
    website: "#"
    github: iLiekatz
    twitter:
    about: "Here's a little about iLiekatz"
    
  inf380pcoder:
    name: inf380pcoder
    prof: false
    gravatar:
    website: "#"
    github: inf380pcoder
    twitter:
    about: "Here's a little about inf380pcoder"
    
  JamesAthrun:
    name: JamesAthrun
    prof: false
    gravatar:
    website: "#"
    github: JamesAthrun
    twitter:
    about: "A second year master student in UT Austin"
    
  JohnCBMeyer:
    name: JohnCBMeyer
    prof: false
    gravatar:
    website: "#"
    github: JohnCBMeyer
    twitter:
    about: "Here's a little about JohnCBMeyer"
    
  jpmartinezutexas:
    name: jpmartinezutexas
    prof: false
    gravatar:
    website: "#"
    github: jpmartinezutexas
    twitter:
    about: "Here's a little about jpmartinezutexas"
    
  JULIIRA:
    name: JULIIRA
    prof: false
    gravatar:
    website: "#"
    github: JULIIRA
    twitter:
    about: "Here's a little about JULIIRA"
    
  manasvini2906:
    name: manasvini2906
    prof: false
    gravatar:
    website: "#"
    github: manasvini2906
    twitter:
    about: "Here's a little about manasvini2906"
    
  martsale:
    name: martsale
    prof: false
    gravatar:
    website: "#"
    github: martsale
    twitter:
    about: "Here's a little about martsale"
    
  mchakerautexas:
    name: mchakerautexas
    prof: false
    gravatar:
    website: "#"
    github: mchakerautexas
    twitter:
    about: "Here's a little about mchakerautexas"
    
  nathanstern93:
    name: nathanstern93
    prof: false
    gravatar:
    website: "#"
    github: nathanstern93
    twitter:
    about: "Here's a little about nathanstern93"
    
  nemothefish260:
    name: nemothefish260
    prof: false
    gravatar:
    website: "#"
    github: nemothefish260
    twitter:
    about: "Here's a little about nemothefish260"
    
  Prakash-sa:
    name: Prakash-sa
    prof: false
    gravatar:
    website: "https://www.linkedin.com/in/sainiprakash525/"
    github: Prakash-sa
    twitter:
    about: "Developer"
    
  Pranithavallabhaneni:
    name: Pranithavallabhaneni
    prof: false
    gravatar:
    website: "#"
    github: Pranithavallabhaneni
    twitter:
    about: "Here's a little about Pranithavallabhaneni"
    
  rabouti:
    name: rabouti
    prof: false
    gravatar:
    website: "#"
    github: rabouti
    twitter:
    about: "Here's a little about rabouti"
    
  RosalindBradshaw:
    name: RosalindBradshaw
    prof: false
    gravatar:
    website: "https://www.youtube.com/watch?v=LLFhKaqnWwk"
    github: RosalindBradshaw
    twitter:
    about: "Second year grad student going into archival work."
    
  Rowan-Loft:
    name: Rowan-Loft
    prof: false
    gravatar:
    website: "https://github.com/Rowan-Loft"
    github: Rowan-Loft
    twitter:
    about: "I'm a Second Year Grad with the I-School going into Library Sciences"
    
  scdai9:
    name: scdai9
    prof: false
    gravatar:
    website: "#"
    github: scdai9
    twitter:
    about: "Here's a little about scdai9"
    
  shashwatj14:
    name: shashwatj14
    prof: false
    gravatar:
    website: "#"
    github: shashwatj14
    twitter:
    about: "Here's a little about shashwatj14"
    
  simon871028:
    name: simon871028
    prof: false
    gravatar:
    website: "#"
    github: simon871028
    twitter:
    about: "Here's a little about simon871028"
    
  Stuks:
    name: Stuks
    prof: false
    gravatar:
    website: "#"
    github: Stuks
    twitter:
    about: "Here's a little about Stuks"
    
  unixEnthusiast:
    name: unixEnthusiast
    prof: false
    gravatar:
    website: "#"
    github: unixEnthusiast
    twitter:
    about: "Here's a little about unixEnthusiast"
    
  zengjilie:
    name: zengjilie
    prof: false
    gravatar:
    website: "#"
    github: zengjilie
    twitter:
    about: "Here's a little about zengjilie"
    
baseurl:
url:
